batch_size: 32
bidirectional: false
checkpoint_dir: checkpoints/lstm
dropout: 0.5
early_stopping: true
epochs: 100
log_dir: logs/lstm
lr: 0.0001
lr_factor: 0.2
lr_patience: 7
lr_scheduler: reduce_on_plateau
lstm_hidden_size: 128
lstm_num_layers: 2
min_delta: 0.0005
min_lr: 1.0e-07
model_type: advanced
patience: 15
project: CDL1-LSTM
restore_best_weights: true
run_name: advanced-bs32-lr0.0001-hs128-nl2-do0.5-biFalse
save_best_only: true
save_frequency: 5
train_val_split: 0.8
use_lr_scheduler: true
use_wandb: false
val_test_split: 0.1
warmup_epochs: 5
weight_decay: 1.0e-05
