batch_size: 64
checkpoint_dir: checkpoints/mlp
dropout: 0.4
early_stopping: true
epochs: 100
log_dir: logs/mlp
lr: 0.0001
lr_factor: 0.2
lr_patience: 7
lr_scheduler: reduce_on_plateau
min_delta: 0.0005
min_lr: 1.0e-07
mlp_hidden_sizes:
- 1024
- 512
- 256
model_type: advanced
patience: 15
project: CDL1-MLP
restore_best_weights: true
run_name: mlp-bs64-lr0.0001-hs1024-do0.4-advanced
save_best_only: true
save_frequency: 5
train_val_split: 0.8
use_lr_scheduler: true
use_wandb: false
val_test_split: 0.1
warmup_epochs: 5
weight_decay: 1.0e-05
